### PR TITLE
fix: fill defaults for non-required field of type "record"

### LINKED ISSUE #334: wrong default filled for non-required field of type "record"
### Problem

 [handle_missing_fields](https://github.com/Kong/kong/blob/241c4d0681c7996e8565e278937838f5ec723273/kong/db/schema/init.lua#L1001) in lua code and [FillPluginsDefaults](https://github.com/Kong/go-kong/blob/3ff328d54ff853d7bf24e5f1ab04adb8fd22a317/kong/utils.go#L510) in go-kong has different handling for default values in the following scenario:
- when the field is of type "record"
- `required` is set to false
- No subconfig provided for that field. 

Kong Gateway fills the default as `nil` but KIC fills the default with a record object with nil fields.
This causes KIC to keep detecting diff and it gets stuck in sync retry loop and ultimately gets OOMKilled.

### PR DESCRIPTION
**Pull request by nishant95**
Fixes #334 

Adds a check for required while recusrively filling defaults for subconfig of type record.
Current behaviour of KIC is out of sync from Kong Lua implementation.

There are some field "required" checks in Lua code: [here](https://github.com/Kong/kong/blob/2a3e9193c37a8df3eb3edae6728fa84b4bfed820/kong/db/schema/init.lua#L1020) and [here](https://github.com/Kong/kong/blob/2a3e9193c37a8df3eb3edae6728fa84b4bfed820/kong/db/schema/init.lua#L1538)
These checks are missing form go code

### CODE REVIEW

**Comment by aboudreault** [comment]
thanks @nishant95! I just tested your branch and I still have the same issue, my field is set to `null`.  My fix in #333 works understand that our PRs don't fix exactly the same thing. To support default with `set` of record, we'll need to merge both, right?

**Comment by nishant95** [comment]
@aboudreault Yes, I raised this PR for issue #334 , this deals with record type only.
Your PR looks good and should fix it for type "set". 

But shouldn't there be a similar handling for type "map" as well? Similar to [this](https://github.com/Kong/kong/blob/750ba978b5ba9234d2ae6d84ac9806904c6cd9bc/kong/db/schema/init.lua#L1576) in Lua.

**Comment by aboudreault** [comment]
@nishant95 this is possible yeah. Let's try to release this fix and #333, I will create a ticket for the map type.

**Review by rainest — APPROVED** [review]

**Comment by rainest** [comment]
Overriding linter failure and merging cause it ain't worth waiting to round trip to the upstream branch and the error is inscrutable:

```
Check failure on line 2262 in kong/utils_test.go
GitHub Actions / lint

File is not `gci`-ed with --skip-generated -s standard -s default -s prefix(github.com/kong) (gci)
```

golangci, please just print the actual command you need to run. Furthermore, the import block didn't change between those commits; it shouldn't start failing. This is not an import >:(

```
10:47:38-0700 esenin $ gci diff --skip-generated  -s standard -s default -s "prefix(github.com/kong)" utils_test.go 
--- utils_test.go
+++ utils_test.go
@@ -2259,4 +2259,4 @@
 			}
 		})
 	}
-}
\ No newline at end of file
+}
```

Going to fix in the release changelog commit.

File: kong/utils_test.go [hunk 1]
```diff
@@ -1671,3 +2079,184 @@ func Test_FillPluginsDefaults_SetType(t *testing.T) {
 		})
 	}
 }
+
+func Test_FillPluginsDefaults_Acme(t *testing.T) {
+	RunWhenKong(t, "==3.3.0")
```
Comment (pmalek) [inline kong/utils_test.go:2084]: Is there a reason we want to run this against 3.3 **only**? If so then I believe this line deserves a comment why that's the case. It's not obvious to the reader why this particular version was chosen here and deserves a special treatment.

Comment (nishant95) [reply kong/utils_test.go:2084]: @pmalek You are right, this check is not needed. This is a residual check which I added initially as the schema for this  plugin changed a lot over different kong versions, this is of no use now as the schema has been added to the test itself.

Comment (pmalek) [reply kong/utils_test.go:2084]: Great! This should fix it then right? #342

Comment (nishant95) [reply kong/utils_test.go:2084]: No, this should fix it: #343 Else the test would fail for many of the kong versions as the schema for Acme plugin would be different.
